<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="PC177" failures="1" tests="2" name="Test(failed)" time="109.98" errors="0" timestamp="2023-04-18T12:51:43 IST">
  <testcase classname="Reports.TestSubTotalForInvoiceReport" name="NumberofInvoice" time="38.321"/>
  <testcase classname="Reports.TestSubTotalForInvoiceReport" name="VerifySubTotalcolumnValueFromwebtable" time="23.067">
    <failure type="java.lang.AssertionError" message="expected [-2] but found [25]">
      <![CDATA[java.lang.AssertionError: expected [-2] but found [25]
at Reports.TestSubTotalForInvoiceReport.VerifySubTotalcolumnValueFromwebtable(TestSubTotalForInvoiceReport.java:176)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifySubTotalcolumnValueFromwebtable -->
  <testcase classname="Reports.TestSubTotalForInvoiceReport" name="VerifysubTotalTitle" time="0.0">
    <ignored/>
  </testcase> <!-- VerifysubTotalTitle -->
  <testcase classname="Reports.TestSubTotalForInvoiceReport" name="VerifySubTotalColumnForInvoiceReport" time="0.0">
    <ignored/>
  </testcase> <!-- VerifySubTotalColumnForInvoiceReport -->
</testsuite> <!-- Test(failed) -->
